version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - CELERY_BROKER=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWD}@rabbitmq:5672/
      - CELERY_BACKEND=rpc://
    depends_on:
      - postgres
      - rabbitmq

  celery:
    build: .
    container_name: celery
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWD}@rabbitmq:5672/
      - CELERY_BACKEND=rpc://
    depends_on:
      - django
      - rabbitmq

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A config beat -l INFO -S django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWD}@rabbitmq:5672/
      - CELERY_BACKEND=rpc://
    depends_on:
      - rabbitmq
      - django
      - celery

  postgres:
    image: postgres:latest
    container_name: db_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
  postgres_data:
