# Generated by Django 5.1.6 on 2025-03-02 00:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('json_result', models.JSONField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slips', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'db_table': 'slips',
                'ordering': ['-created_at'],
            },
        ),
    ]
