# Generated by Django 5.1.6 on 2025-03-02 00:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlipMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delinquent_due', models.BooleanField(default=False)),
                ('send_due', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('date_vencit', models.DateField()),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='slips.slip')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'slip_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
