# Generated by Django 5.1.6 on 2025-03-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slipmessage',
            name='delinquent_due',
            field=models.CharField(choices=[('YY', 'Yes'), ('NN', 'No')], default='NN', max_length=2),
        ),
    ]
