# Generated by Django 5.1.6 on 2025-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0002_alter_slipmessage_delinquent_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slipmessage',
            name='delinquent_due',
            field=models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2),
        ),
    ]
